チャット画面のフロント実装
mgmmy/chat-space pull request #2
Opened 2019-04-13 08:47 UTC by mgmmy

#What
-サイドバー（グループ一覧の表示）
-チャット（メッセージの表示）
-メッセージフォーム（メッセージの投稿）

#Why
アプリケーションに必須の機能のため

2019-04-13 09:14 UTC, ato-tech approved these changes

2019-04-13 09:14 UTC, ato-tech commented on app/assets/stylesheets/style.scss
> +  float: left;
このfloatをクリアするclearfixなどは使われてますでしょうか？見当たりませんでしたので...
見落としでしたら無視してください！

2019-04-13 09:14 UTC, ato-tech commented on app/views/layouts/application.html.haml
> +      .chat-side
サイドは部分テンプレートにした方が良いかと思います！

2019-04-13 09:14 UTC, ato-tech commented on app/views/layouts/application.html.haml
> +              %a{ :href => "" }<
リンク先は仮置きで良いので、link_toで書きましょう！

2019-04-13 09:14 UTC, ato-tech commented on app/views/layouts/application.html.haml
> +            %li.user-menu__new-group<
ちょこちょこタグの最後に<があるのですが不要でしたら消しましょう！

2019-04-13 09:14 UTC, ato-tech commented on app/views/layouts/application.html.haml
> +            %input{ :name => "utf8", :type => "hidden", :value => "✓" }
ハッシュロケットは古い記法なのでやめましょう！

2019-04-13 09:40 UTC, mgmmy commented on app/assets/stylesheets/style.scss
> +  float: left;
clearfixは仕様していません。
表示に問題がなさそうなのですが、一応追加したほうがいいのでしょうか？

2019-04-13 10:38 UTC, mgmmy commented on app/views/layouts/application.html.haml
> +            %input{ :name => "utf8", :type => "hidden", :value => "✓" }
修正しました。

2019-04-13 10:40 UTC, mgmmy commented on app/views/layouts/application.html.haml
> +            %li.user-menu__new-group<
タグの改行をしないようにする記述なので必要と思ったのですが、
とくに気にしなくて良さそうなので削除しました。

2019-04-13 10:40 UTC, mgmmy commented on app/views/layouts/application.html.haml
> +              %a{ :href => "" }<
修正しました。

2019-04-14 03:02 UTC, mgmmy commented on app/views/layouts/application.html.haml
> +      .chat-side
修正しました。

2019-04-14 03:07 UTC, yuki-uchida requested changes

2019-04-14 03:07 UTC, yuki-uchida commented on app/assets/stylesheets/style.scss
> +.chat-side {
BEMに沿ったクラス命名を行い、アンバサンドを活用した省略系で記述してください

サンプルページのHTMLに惑わされないようにしましょう

2019-04-14 03:07 UTC, yuki-uchida commented on app/assets/stylesheets/style.scss
> +    .group {
この辺りも

2019-04-14 03:07 UTC, yuki-uchida commented on app/assets/stylesheets/style.scss
> +  .main-header {
この辺りも

2019-04-14 05:05 UTC, mgmmy commented on app/assets/stylesheets/style.scss
> +.chat-side {
修正しました。

2019-04-14 05:05 UTC, mgmmy commented on app/assets/stylesheets/style.scss
> +    .group {
修正しました。

2019-04-14 05:05 UTC, mgmmy commented on app/assets/stylesheets/style.scss
> +  .main-header {
修正しました。

2019-04-14 05:09 UTC, ghost approved these changes
LGTMです！

2019-04-14 05:10 UTC, merged